name: RTD
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip>=22
  - pip:
      - sphinx-rtd-theme>=1.0.0
      - h5py>=3.9.0
      - matplotlib>=3.7
      - numpy>=1.18
      - pandas>=1.0
      - commentjson>=0.9.0
